default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: timetracker_development

test:
  <<: *default
  host: localhost
  database: timetracker_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
