# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dc684399bf28c097da4b38953b8243c2af1c350f18d064919ff800e4e7bb08ee2959553da71bce142b03f220cf3312e0789955a36826a3b8497c373ee083b37

test:
  secret_key_base: 73db535c682f7249e6dbe25aa9ebba737b2ffe57b463fb7eddf5f8b9add5d9b1f91ac2edec28c8d16fc21548ea359e9ab0f8633b0d8585155fad0f08680ea20e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
